#!/usr/bin/env python3
"""Generate the insect-war-schematics companion series (task 193).

Vintage engineering schematics / patent-drawing blueprints documenting how to
BUILD selected machines from the insect-war series (tasks 189/191). Each sheet
is generated by feeding the actual creature image to gemini-2.5-flash-image as
an input image plus a drafting instruction, so the schematic matches that
specific machine's anatomy.

Writes to /home/devin/src/2026/midi/generated/insect-war-schematics/:
  respNN.json              raw generateContent response
  schematic_NN.png         decoded color master
  schematic_NN_aged.png    aged-paper treatment (ffmpeg)
"""
import base64
import json
import os
import subprocess
import sys
import urllib.request

SRC = "/home/devin/src/2026/midi/generated/insect-war"
OUT = "/home/devin/src/2026/midi/generated/insect-war-schematics"
MODEL = "gemini-2.5-flash-image"
KEY = os.environ["GEMINI_API_KEY"]
URL = f"https://generativelanguage.googleapis.com/v1beta/models/{MODEL}:generateContent?key={KEY}"

NO_TEXT = ("CRITICAL: absolutely no real readable text anywhere on the sheet — "
           "every label, dimension, note, and title-block entry is illegible "
           "pseudo-English glyphs and draftsman's marks that only suggest writing.")

BASE = ("Redraw the machine in this photograph as a photorealistic vintage "
        "ENGINEERING SCHEMATIC sheet — a mid-century defense contractor's "
        "patent-style construction blueprint for building this exact machine, "
        "1950s hand-draftsmanship ethos documenting futuristic year-3050 "
        "technology. Faithfully preserve this specific machine's anatomy, "
        "proportions and mechanisms. The sheet shows: precise orthographic "
        "line-drawing views (side elevation, top plan, front view), cutaway "
        "and exploded views of internal mechanisms, dimension lines with "
        "arrows, callout circles with magnified detail insets, section "
        "hatching, and a ruled title block in the lower corner. ")

STYLES = {
    "cyanotype": ("Style: classic cyanotype blueprint — crisp white and "
                  "pale-blue linework on deep Prussian-blue paper, faint "
                  "grid, slight print streaks. "),
    "vellum": ("Style: black and sepia ink on aged ivory vellum drafting "
               "paper, ruled border, faint pencil construction lines, "
               "coffee-toned stains at the edges. "),
    "newsprint": ("Style: aged technical-manual page on yellowed newsprint, "
                  "dense black ink linework with halftone shading, slight "
                  "ink bleed, fold creases. "),
}

# (source image, style, machine-specific drafting focus)
SHEETS = [
    ("insect_war_05.png", "cyanotype",
     "Subject: the praying-mantis war machine on the left of the photo (ignore "
     "the beetle opponent entirely). Draw exactly ONE mantis machine — never "
     "two facing each other. Detail the serrated scythe-arm assemblies, elbow "
     "hydraulics, segmented neck articulation, and leg linkages."),

    ("insect_war_07.png", "vellum",
     "Subject: the large stag-beetle war machine with glowing headlamp eyes "
     "(ignore the small ants). Detail the riveted dome carapace armor plates, "
     "the pincer mandible drive gears, headlamp housings, and six-leg "
     "suspension linkages."),

    ("insect_war_08.png", "cyanotype",
     "Subject: the hovering dragonfly gunship. Detail the four transparent "
     "alloy wings and their root actuator gearboxes, the segmented vertebral "
     "tail with its articulation joints, underslung sensor and weapon pods, "
     "and cockpit canopy section."),

    ("insect_war_10.png", "vellum",
     "Subject: the mechanical hornet head assembly. A head-unit construction "
     "sheet: exploded view of the hexagonal-lens compound eye stacks, riveted "
     "face plates, titanium mandible pivots, antenna segment joints, and the "
     "anatomical human-finger palp grafts with their tendon-cable runs shown "
     "in cutaway."),

    ("insect_war_18.png", "newsprint",
     "Subject: the large wasp bomber machine in the foreground. Detail the "
     "wing spars and membranes, the segmented steel abdomen with its bomblet "
     "release bay shown open in cutaway with the glowing ovoid bomblets "
     "racked inside, dangling landing legs, and thorax engine section."),

    ("insect_war_19.png", "vellum",
     "Subject: the battle-scarred grasshopper war machine. Detail the riveted "
     "head and thorax armor plates, antenna mounts, the powerful folded "
     "jumping leg mechanism with spring accumulators, and the anatomical "
     "human-hand forelimb grafts with wrist interface collars shown in "
     "exploded view."),

    ("insect_war_20.png", "newsprint",
     "Subject: the crawling beetle machine with a human face beneath its "
     "helmet plating. Detail the domed riveted helmet-carapace plates shown "
     "lifted in exploded view above the anatomical human face interface, the "
     "many trailing segmented cable-tentacle limbs with their root sockets, "
     "and the forward digging claw. Write every annotation, view name and "
     "title-block entry in a fictional invented script of angular alien "
     "symbols — do not use the Latin alphabet at all, zero English letters "
     "anywhere on the sheet."),

    ("insect_war_21.png", "cyanotype",
     "Subject: the small assassin-bug machine. Detail the needle proboscis "
     "injector assembly in longitudinal section, the segmented polished "
     "thorax with the row of grafted human ears and their mounting recesses, "
     "the human-thumb foreleg tips, and the slender jointed legs. Write "
     "every annotation, view name and title-block entry in a fictional "
     "invented script of angular alien symbols — do not use the Latin "
     "alphabet at all, zero English letters anywhere on the sheet."),

    ("insect_war_23.png", "vellum",
     "Subject: the toppled house-sized queen machine. Detail the segmented "
     "wormlike chrome abdomen hull rings, the internal larva-production "
     "galleries shown in long cutaway with racked larva machines and the "
     "anatomical human limb components, and the forward turbine head unit."),
]

# period aging that keeps each sheet's paper color (no desaturation, no
# color cast — a warm shift hazes the cyanotype sheets): mild contrast dig,
# print grain, forward vignette so corners darken
AGE = ("curves=master='0/0 0.5/0.48 1/0.98',"
       "noise=alls=12:allf=t+u,gblur=sigma=0.3,"
       "vignette=PI/4.8:dither=1")


def generate(i, src, style, focus):
    with open(f"{SRC}/{src}", "rb") as f:
        img_b64 = base64.b64encode(f.read()).decode()
    prompt = BASE + STYLES[style] + focus + " " + NO_TEXT
    body = json.dumps({
        "contents": [{"parts": [
            {"inlineData": {"mimeType": "image/png", "data": img_b64}},
            {"text": prompt},
        ]}],
        "generationConfig": {"responseModalities": ["IMAGE"]},
    }).encode()
    req = urllib.request.Request(URL, data=body,
                                 headers={"Content-Type": "application/json"})
    raw = urllib.request.urlopen(req, timeout=180).read()
    resp_path = f"{OUT}/resp{i:02d}.json"
    with open(resp_path, "wb") as f:
        f.write(raw)
    resp = json.loads(raw)
    for part in resp["candidates"][0]["content"]["parts"]:
        inline = part.get("inlineData") or part.get("inline_data")
        if inline:
            png = f"{OUT}/schematic_{i:02d}.png"
            with open(png, "wb") as f:
                f.write(base64.b64decode(inline["data"]))
            return png
    raise RuntimeError(f"no image part in resp{i:02d}.json")


def age(png):
    out = png.replace(".png", "_aged.png")
    subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", png,
                    "-vf", AGE, out], check=True)
    return out


def main():
    os.makedirs(OUT, exist_ok=True)
    only = [int(a) for a in sys.argv[1:]]  # optional: retry specific indices
    for i, (src, style, focus) in enumerate(SHEETS, start=1):
        if only and i not in only:
            continue
        if not only and os.path.exists(f"{OUT}/schematic_{i:02d}.png"):
            print(f"[{i:02d}] exists, skipping")
            continue
        try:
            png = generate(i, src, style, focus)
            aged = age(png)
            print(f"[{i:02d}] OK  {os.path.basename(png)}  {os.path.basename(aged)}")
        except Exception as e:
            print(f"[{i:02d}] FAIL {e}")


if __name__ == "__main__":
    main()
